# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Version.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Version.proto',
  package='version_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rVersion.proto\x12\rversion_proto\x1a\x1bgoogle/protobuf/empty.proto\"u\n\x08Versions\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05names\x18\x02 \x01(\t\x12\x11\n\tcodeBases\x18\x03 \x01(\t\x12\x10\n\x08versions\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63tiveStates\x18\x05 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"\x15\n\x13VersionsListRequest\"%\n\x17VersionsRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xe6\x02\n\x12VersionsController\x12G\n\x04List\x12\".version_proto.VersionsListRequest\x1a\x17.version_proto.Versions\"\x00\x30\x01\x12<\n\x06\x43reate\x12\x17.version_proto.Versions\x1a\x17.version_proto.Versions\"\x00\x12M\n\x08Retrieve\x12&.version_proto.VersionsRetrieveRequest\x1a\x17.version_proto.Versions\"\x00\x12<\n\x06Update\x12\x17.version_proto.Versions\x1a\x17.version_proto.Versions\"\x00\x12<\n\x07\x44\x65stroy\x12\x17.version_proto.Versions\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_VERSIONS = _descriptor.Descriptor(
  name='Versions',
  full_name='version_proto.Versions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='version_proto.Versions.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='version_proto.Versions.names', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codeBases', full_name='version_proto.Versions.codeBases', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versions', full_name='version_proto.Versions.versions', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activeStates', full_name='version_proto.Versions.activeStates', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='version_proto.Versions.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=178,
)


_VERSIONSLISTREQUEST = _descriptor.Descriptor(
  name='VersionsListRequest',
  full_name='version_proto.VersionsListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=201,
)


_VERSIONSRETRIEVEREQUEST = _descriptor.Descriptor(
  name='VersionsRetrieveRequest',
  full_name='version_proto.VersionsRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='version_proto.VersionsRetrieveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=240,
)

DESCRIPTOR.message_types_by_name['Versions'] = _VERSIONS
DESCRIPTOR.message_types_by_name['VersionsListRequest'] = _VERSIONSLISTREQUEST
DESCRIPTOR.message_types_by_name['VersionsRetrieveRequest'] = _VERSIONSRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Versions = _reflection.GeneratedProtocolMessageType('Versions', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONS,
  '__module__' : 'Version_pb2'
  # @@protoc_insertion_point(class_scope:version_proto.Versions)
  })
_sym_db.RegisterMessage(Versions)

VersionsListRequest = _reflection.GeneratedProtocolMessageType('VersionsListRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONSLISTREQUEST,
  '__module__' : 'Version_pb2'
  # @@protoc_insertion_point(class_scope:version_proto.VersionsListRequest)
  })
_sym_db.RegisterMessage(VersionsListRequest)

VersionsRetrieveRequest = _reflection.GeneratedProtocolMessageType('VersionsRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONSRETRIEVEREQUEST,
  '__module__' : 'Version_pb2'
  # @@protoc_insertion_point(class_scope:version_proto.VersionsRetrieveRequest)
  })
_sym_db.RegisterMessage(VersionsRetrieveRequest)



_VERSIONSCONTROLLER = _descriptor.ServiceDescriptor(
  name='VersionsController',
  full_name='version_proto.VersionsController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=243,
  serialized_end=601,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='version_proto.VersionsController.List',
    index=0,
    containing_service=None,
    input_type=_VERSIONSLISTREQUEST,
    output_type=_VERSIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='version_proto.VersionsController.Create',
    index=1,
    containing_service=None,
    input_type=_VERSIONS,
    output_type=_VERSIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='version_proto.VersionsController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_VERSIONSRETRIEVEREQUEST,
    output_type=_VERSIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='version_proto.VersionsController.Update',
    index=3,
    containing_service=None,
    input_type=_VERSIONS,
    output_type=_VERSIONS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='version_proto.VersionsController.Destroy',
    index=4,
    containing_service=None,
    input_type=_VERSIONS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERSIONSCONTROLLER)

DESCRIPTOR.services_by_name['VersionsController'] = _VERSIONSCONTROLLER

# @@protoc_insertion_point(module_scope)
