# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Versioning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Versioning.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10Versioning.proto\"\x1e\n\x10VersionIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"s\n\x12PostVersionRequest\x12\r\n\x05names\x18\x01 \x01(\t\x12\x11\n\tcodeBases\x18\x02 \x01(\t\x12\x10\n\x08versions\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tiveStates\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"~\n\x11PutVersionRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05names\x18\x02 \x01(\t\x12\x11\n\tcodeBases\x18\x03 \x01(\t\x12\x10\n\x08versions\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63tiveStates\x18\x05 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"\x18\n\x16GetMultiVersionRequest\"\xa4\x01\n\x13VersionDataResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05names\x18\x02 \x01(\t\x12\x11\n\tcodeBases\x18\x03 \x01(\t\x12\x10\n\x08versions\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63tiveStates\x18\x05 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x10\n\x08\x63reateAt\x18\x07 \x01(\t\x12\x10\n\x08updateAt\x18\x08 \x01(\t\"\'\n\x15\x44\x65leteVersionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"@\n\x17GetMultiVersionResponse\x12%\n\x07version\x18\x01 \x03(\x0b\x32\x14.VersionDataResponse2\x8f\x03\n\x11VersioningService\x12=\n\x10getSingleVersion\x12\x11.VersionIdRequest\x1a\x14.VersionDataResponse\"\x00\x12\x46\n\x0fgetMultiVersion\x12\x17.GetMultiVersionRequest\x1a\x18.GetMultiVersionResponse\"\x00\x12<\n\rdeleteVersion\x12\x11.VersionIdRequest\x1a\x16.DeleteVersionResponse\"\x00\x12?\n\x12\x66orceDeleteVersion\x12\x11.VersionIdRequest\x1a\x14.VersionDataResponse\"\x00\x12:\n\x0bpostVersion\x12\x13.PostVersionRequest\x1a\x14.VersionDataResponse\"\x00\x12\x38\n\nputVersion\x12\x12.PutVersionRequest\x1a\x14.VersionDataResponse\"\x00\x62\x06proto3'
)




_VERSIONIDREQUEST = _descriptor.Descriptor(
  name='VersionIdRequest',
  full_name='VersionIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VersionIdRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_POSTVERSIONREQUEST = _descriptor.Descriptor(
  name='PostVersionRequest',
  full_name='PostVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='PostVersionRequest.names', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codeBases', full_name='PostVersionRequest.codeBases', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versions', full_name='PostVersionRequest.versions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activeStates', full_name='PostVersionRequest.activeStates', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='PostVersionRequest.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=167,
)


_PUTVERSIONREQUEST = _descriptor.Descriptor(
  name='PutVersionRequest',
  full_name='PutVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PutVersionRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='PutVersionRequest.names', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codeBases', full_name='PutVersionRequest.codeBases', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versions', full_name='PutVersionRequest.versions', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activeStates', full_name='PutVersionRequest.activeStates', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='PutVersionRequest.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=295,
)


_GETMULTIVERSIONREQUEST = _descriptor.Descriptor(
  name='GetMultiVersionRequest',
  full_name='GetMultiVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=321,
)


_VERSIONDATARESPONSE = _descriptor.Descriptor(
  name='VersionDataResponse',
  full_name='VersionDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VersionDataResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='VersionDataResponse.names', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codeBases', full_name='VersionDataResponse.codeBases', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versions', full_name='VersionDataResponse.versions', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activeStates', full_name='VersionDataResponse.activeStates', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='VersionDataResponse.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createAt', full_name='VersionDataResponse.createAt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updateAt', full_name='VersionDataResponse.updateAt', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=488,
)


_DELETEVERSIONRESPONSE = _descriptor.Descriptor(
  name='DeleteVersionResponse',
  full_name='DeleteVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='DeleteVersionResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=529,
)


_GETMULTIVERSIONRESPONSE = _descriptor.Descriptor(
  name='GetMultiVersionResponse',
  full_name='GetMultiVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='GetMultiVersionResponse.version', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=595,
)

_GETMULTIVERSIONRESPONSE.fields_by_name['version'].message_type = _VERSIONDATARESPONSE
DESCRIPTOR.message_types_by_name['VersionIdRequest'] = _VERSIONIDREQUEST
DESCRIPTOR.message_types_by_name['PostVersionRequest'] = _POSTVERSIONREQUEST
DESCRIPTOR.message_types_by_name['PutVersionRequest'] = _PUTVERSIONREQUEST
DESCRIPTOR.message_types_by_name['GetMultiVersionRequest'] = _GETMULTIVERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionDataResponse'] = _VERSIONDATARESPONSE
DESCRIPTOR.message_types_by_name['DeleteVersionResponse'] = _DELETEVERSIONRESPONSE
DESCRIPTOR.message_types_by_name['GetMultiVersionResponse'] = _GETMULTIVERSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionIdRequest = _reflection.GeneratedProtocolMessageType('VersionIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONIDREQUEST,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:VersionIdRequest)
  })
_sym_db.RegisterMessage(VersionIdRequest)

PostVersionRequest = _reflection.GeneratedProtocolMessageType('PostVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTVERSIONREQUEST,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:PostVersionRequest)
  })
_sym_db.RegisterMessage(PostVersionRequest)

PutVersionRequest = _reflection.GeneratedProtocolMessageType('PutVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTVERSIONREQUEST,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:PutVersionRequest)
  })
_sym_db.RegisterMessage(PutVersionRequest)

GetMultiVersionRequest = _reflection.GeneratedProtocolMessageType('GetMultiVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIVERSIONREQUEST,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:GetMultiVersionRequest)
  })
_sym_db.RegisterMessage(GetMultiVersionRequest)

VersionDataResponse = _reflection.GeneratedProtocolMessageType('VersionDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONDATARESPONSE,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:VersionDataResponse)
  })
_sym_db.RegisterMessage(VersionDataResponse)

DeleteVersionResponse = _reflection.GeneratedProtocolMessageType('DeleteVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEVERSIONRESPONSE,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:DeleteVersionResponse)
  })
_sym_db.RegisterMessage(DeleteVersionResponse)

GetMultiVersionResponse = _reflection.GeneratedProtocolMessageType('GetMultiVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIVERSIONRESPONSE,
  '__module__' : 'Versioning_pb2'
  # @@protoc_insertion_point(class_scope:GetMultiVersionResponse)
  })
_sym_db.RegisterMessage(GetMultiVersionResponse)



_VERSIONINGSERVICE = _descriptor.ServiceDescriptor(
  name='VersioningService',
  full_name='VersioningService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=598,
  serialized_end=997,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSingleVersion',
    full_name='VersioningService.getSingleVersion',
    index=0,
    containing_service=None,
    input_type=_VERSIONIDREQUEST,
    output_type=_VERSIONDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getMultiVersion',
    full_name='VersioningService.getMultiVersion',
    index=1,
    containing_service=None,
    input_type=_GETMULTIVERSIONREQUEST,
    output_type=_GETMULTIVERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteVersion',
    full_name='VersioningService.deleteVersion',
    index=2,
    containing_service=None,
    input_type=_VERSIONIDREQUEST,
    output_type=_DELETEVERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='forceDeleteVersion',
    full_name='VersioningService.forceDeleteVersion',
    index=3,
    containing_service=None,
    input_type=_VERSIONIDREQUEST,
    output_type=_VERSIONDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='postVersion',
    full_name='VersioningService.postVersion',
    index=4,
    containing_service=None,
    input_type=_POSTVERSIONREQUEST,
    output_type=_VERSIONDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='putVersion',
    full_name='VersioningService.putVersion',
    index=5,
    containing_service=None,
    input_type=_PUTVERSIONREQUEST,
    output_type=_VERSIONDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERSIONINGSERVICE)

DESCRIPTOR.services_by_name['VersioningService'] = _VERSIONINGSERVICE

# @@protoc_insertion_point(module_scope)
