# Generated by Django 3.2.9 on 2021-11-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('codeBases', models.CharField(max_length=50)),
                ('versions', models.CharField(max_length=10)),
                ('activeStates', models.BooleanField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('deleteAt', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
