# Generated by Django 3.2.9 on 2021-11-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Version', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='versions',
            table='Versions',
        ),
    ]
